name: Python App CI/CD

on:
  push:
    branches:
      - parking/cleaver
  pull_request:
    branches:
      - parking/cleaver

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim
      options: --user root

    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: best_parking_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      db_test:
        image: postgres:17.2
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - "5433:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gunicorn in background
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: best_parking_db
          TESTING: "False"
        run: |
          gunicorn --bind 0.0.0.0:5000 wsgi:app &
          sleep 5  # Подождите, пока Gunicorn запустится

      - name: Run tests
        env:
          DB_USER: test
          DB_PASSWORD: test
          POSTGRES_HOST: db_test
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
          TESTING: "True"
        run: |
          pytest tests/

      - name: Stop Gunicorn
        run: |
          pkill -f gunicorn
