name: Python App CI/CD

on:
  push:
    branches:
      - parking/cleaver
  pull_request:
    branches:
      - parking/cleaver

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m venv /venv
        source /venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run ruff
      run: |
        ruff check --fix .
    - name: Run isort
      run: |
        isort . 
        
    - name: Docker build and run
      run: |
        docker compose up --build -d
        
    - name: Docker exec
      run: |
        docker exec -it best_parking-web-1 bash

    - name: Pytest
      run: |
        pytest

    - name: Finish workflow
      run: |
        exit
        docker compose down -v
