name: Python App CI/CD

on:
  push:
    branches:
      - parking/cleaver
  pull_request:
    branches:
      - parking/cleaver

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim
      options: --user root

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      db_test:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - "5433:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gunicorn in background
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: best_parking_db
          TESTING: "False"
        run: |
          gunicorn --bind 0.0.0.0:5000 wsgi:app &
          sleep 5  # Подождите, пока Gunicorn запустится

      - name: Connect to PostgreSQL
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          echo "Connected to PostgreSQL"

      - name: Run tests
        env:
          DB_USER: test
          DB_PASSWORD: test
          POSTGRES_HOST: db_test
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
          TESTING: "True"
          TEST_DB_URI: "postgresql://test:test@db_test:5432/test_db"
        run: |
          pytest 

      - name: Stop Gunicorn
        run: |
          pkill -f gunicorn


      - name: Stop Gunicorn
        run: |
          pkill -f gunicorn

